#%RAML 1.0
title: Database API
version: v1
baseUri: http://localhost:8085/api
mediaType: application/json

/health:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              { "status": "UP", "service": "api-database", "port": 8085 }

/orders:
  post:
    body:
      application/json:
        example:
          {
            "orderId": "ORD1001",
            "customerId": "CUS101",
            "product": "Laptop",
            "quantity": 2,
            "amount": 85000,
            "priority": true,
            "email": "customer@example.com"
          }
    responses:
      201:
        body:
          application/json:
            example:
              {
                "orderId": "ORD1001",
                "status": "PERSISTED",
                "message": "Order successfully recorded in database"
              }
